-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE STOCK_PRED_ROLE;
GRANT ROLE STOCK_PRED_ROLE TO ROLE SYSADMIN;
GRANT ROLE STOCK_PRED_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE STOCK_PRED_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE STOCK_PRED_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE STOCK_PRED_ROLE;

-- Databases
CREATE OR REPLACE DATABASE STOCK_PRED_DB;
GRANT OWNERSHIP ON DATABASE STOCK_PRED_DB TO ROLE STOCK_PRED_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE STOCK_PRED_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE STOCK_PRED_WH TO ROLE STOCK_PRED_ROLE;

--Create Schema
CREATE OR REPLACE SCHEMA STOCK_PRED_SCHEMA;

--Create a table to store prices 
create or replace table historical_prices
(
High float,
Low float,
Open float,
Close float,
Volume integer,
AdjClose float,
Date Date,
Ticker varchar
);